version: '3.11'
services:
  vosk-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: speech-parser-gpu
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      # - CUDA_VISIBLE_DEVICES=0
    volumes:
      - .:/app
      - ./models:/app/models
      - ./config:/app/config
      - ./scripts:/app/scripts
      - ./sources:/app/sources
      - ./audio_files:/app/audio_files
      - ./output:/app/output # Output folder for transcription
    working_dir: /app
    command: bash -c "nvidia-smi && python3 main.py && tail -f /dev/null"
    ports:
      - "2700:2700"
    deploy:
      resources:
        limits:
          memory: 26g  # 26 GB limit
          cpus: "6.0"  # 6 CPUs limit
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
